### ISSUE TITLE
Cannot build unless timedata is already built

### ISSUE THREAD

**Issue by adammhaile** [timedata-org/timedata#129]
If you have a fresh clone of the repo, you cannot build because it tries to import the benchmarks, but those try to import timedata, which doesn't exist yet... 

Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    from timedata_build import COMMANDS, CONFIG, FLAGS
  File "src/py\timedata_build\__init__.py", line 2, in <module>
    from . commands import COMMANDS
  File "src/py\timedata_build\commands\__init__.py", line 1, in <module>
    from . Benchmark import Benchmark
  File "src/py\timedata_build\commands\Benchmark.py", line 3, in <module>
    from benchmark.benchmark import run_benchmarks
  File "src/py\benchmark\benchmark.py", line 18, in <module>
    from . benchmarks import biblio, lists, pure_python
  File "src/py\benchmark\benchmarks\lists.py", line 1, in <module>
    from timedata import Color, ColorList
ImportError: No module named 'timedata'

Tried fixing this one only to get another in a different benchmark file.

**Comment by rec** [comment]
Urg, that's annoying!  :-)

Thanks for catching it - I'll fix it instantly.

**Comment by rec** [comment]
There was an issue that masked this one, #130, which I also fixed..
